name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
      
    - name: Pack
      run: dotnet pack Ottergen/Ottergen.csproj --configuration Release --no-build --output nupkg

    - name: Push Package to NuGet.org
      run: dotnet nuget push nupkg/*.nupkg -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json
